2/QRScanner
MiguelWTangF/AppAtemporal-Eq2 pull request #25
Opened 2022-09-18 01:39 UTC by AlejandroRuizZ

Funcionalidad de escaneo de codigo QR con Validacion de si el Boleto fue escaneado previamente, implementado en CLEAN, habilitacion de Camara y orientacion.

2022-09-18 01:40 UTC, AlejandroRuizZ commented
Hola :)

2022-09-18 02:13 UTC, MiguelWTangF requested changes
Bastante bien, nada más atento a los comentarios que les dejé

2022-09-18 02:13 UTC, MiguelWTangF commented on app/src/main/java/com/example/appatemporal/domain/FirestoreService.kt
> +import android.widget.Toast
Limpien imports que no utilizan por ejemplo la línea 5

2022-09-18 02:13 UTC, MiguelWTangF commented on app/src/main/java/com/example/appatemporal/framework/view/RegisterQRView.kt
> +        val scanQRViewModel : ScanQRViewModel by viewModels()
variable scanQRViewModel declarenla arriba en la línea 17 (antes del overridefun) de la siguiente manera, porque así como lo tienen, solo pueden acceder al viewModel en la función onActivityResult:

`private lateinit val scanQRViewModel : ScanQRViewModel by viewModels()`

2022-09-19 01:18 UTC, MiguelWTangF requested changes

2022-09-19 01:18 UTC, MiguelWTangF commented on app/src/main/java/com/example/appatemporal/framework/view/RegisterQRView.kt
> +    val scanQRViewModel : ScanQRViewModel by viewModels()
declarenlo como private late init, sino no les va a funcionar el código y les va a marcar error cuando lo corran literal como se los había puesto en el comentario

`private lateinit val scanQRViewModel : ScanQRViewModel by viewModels()`

2022-09-19 01:41 UTC, MiguelWTangF approved these changes
Aprobado

2022-09-19 01:41 UTC, merged